GITHUB_REPO=https://github.com/IRONKAGE/goit-devops-hw-10.git
# УВАГА: 172.18.0.2 - це зазвичай IP-адреса LocalStack у мережі Docker.
# Якщо Kaniko не зможе достукатися, перевірте IP через: docker inspect localstack_main_hw_10
ECR_REGISTRY=172.18.0.2:4566
REPO_NAME=django-app-hw10-dev
