GITHUB_REPO=https://github.com/IRONKAGE/goit-devops-hw-10.git
AWS_REGION=eu-central-1
REPO_NAME=django-app-hw10-prod

CLUSTER_NAME=goit-eks-hw10-prod
AWS_LBC_ROLE_ARN=arn:aws:iam::AWS_ACCOUNT_ID:role/aws-lbc-role
ESO_ROLE_ARN=arn:aws:iam::AWS_ACCOUNT_ID:role/eso-role
KARPENTER_ROLE_ARN=arn:aws:iam::AWS_ACCOUNT_ID:role/karpenter-controller-role
