{{- if eq .Values.environment "prod" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: django-db-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: django-db-credentials # Створить Secret з ТАКИМ ЖЕ іменем, як у dev!
    creationPolicy: Owner
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: prod/django/database
      property: password
  - secretKey: DB_USER
    remoteRef:
      key: prod/django/database
      property: username
{{- end }}
