# =========================================================================
# 1. БАЗОВИЙ СЕКРЕТ ЗАСТОСУНКУ (Створюється ЗАВЖДИ: і в Dev, і в Prod)
# =========================================================================
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  # Цей ключ обов'язковий для Django завжди
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | b64enc | quote }}

---

# =========================================================================
# 2. СЕКРЕТ БАЗИ ДАНИХ (Створюється ТІЛЬКИ ДЛЯ DEV)
# =========================================================================
{{- if ne .Values.environment "prod" }}
apiVersion: v1
kind: Secret
metadata:
  name: django-db-credentials
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc | quote }}

  # Користувача можемо залишити захардкодженим (admin) або теж брати з values.
  DB_USER: "YWRtaW4=" # "YWRtaW4=" - це admin
{{- end }}
